export enum OrderStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  CONFIRMED = "CONFIRMED",
  SHIPPING = "SHIPPING",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
  REFUND_REQUESTED = "REFUND REQUESTED",
  REFUNDED = "REFUNDED",
}

export enum OrderPaymentType {
  COD = "COD",
  BANKING = "BANKING",
}
